### ISSUE TITLE
Deleting Sensitive Information from Repositories

### ISSUE THREAD

**Issue by angrygoats** [Originate/git-town#1088]
I think it would be useful to add to the set of auxiliary tools the ability to delete sensitive data from the repository like passwords, etc. 

[Github](https://help.github.com/articles/removing-sensitive-data-from-a-repository/) has a useful guide that has this command: 

```sh
 git filter-branch --force --index-filter \
'git rm --cached --ignore-unmatch PATH-TO-YOUR-FILE-WITH-SENSITIVE-DATA' \
--prune-empty --tag-name-filter cat -- --all
```

and it works _great_. It would be super cool though if we could have this built into git town. Maybe a command like:

`git town shred PATH_TO_FILE`. What do you think?

@matthandlersux @kevgo @charlierudolph

**Comment by kevgo** [comment]
Hey @angrygoats, thanks for the suggestion! Interesting functionality. I am, however, against adding this to Git Town for the following reasons:
1. this goes beyond the scope of Git Town as a tool to automate Git branch management in ways to minimize merge conflicts. I don't want Git Town to become a bloated "everything-and-the-kitchen-sink" tool but stay lean, focused on doing its mission, with a small as possible learning curve. It's okay to use several complementary Git tools as a developer. If anything, we should remove some commands from Git Town at this point  :)
2. this is for extremely rare use cases, which hopefully never happen at all. Git Town is for everyday use cases and maybe the occasional once-a-month use case. 
3. this doesn't work for public repos, because they cannot alter history. If one does it anyways it's futile. This also shouldn't be needed for repositories that do code reviews.
3. there is already a single command-line command for Git that does this, plus an apparently [pretty well-done tool](https://rtyley.github.io/bfg-repo-cleaner) with an active community. We don't want to fragment the Git tool landscape unnecessarily and reinvent all the thinking, testing, documentation, and optimizations that went into BFG. I am sure there are a ton of edge cases and things to consider here, and we have very little background around any of those.

If you have a need for this functionality, can you just use BFG? If BFG doesn't do what you want, can you send them a pull request with improvements?
