### ISSUE TITLE
do not exit on conflict

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#1118]
Our current approach to conflicts are to save state to disk, and exit. We then have the user continue / abort. I think it would be nicer if we displayed a prompt giving the user the choice to abort / resolve conflicts and then continue. This also prevents something I have done many times which is to accidentally start a new sync instead of continuing a sync after resolving conflicts.

The undo functionality would still save state to disk.

This would resolve #1016

@kevgo thoughts?

**Comment by charlierudolph** [comment]
Hmm. Less certain about this. I usually run `git status'  and then add the conflicting files. Sometimes I end up changing other files to. Closing

**Comment by kevgo** [comment]
The problem with keeping on running is that it blocks the terminal. Then the user has to open another terminal to resolve the conflicts, then go back to this terminal. I think this is a sub-optimal user experience. 

What I find confusing is that I have to provide the exact same command again in order to continue or abort. Example:
- I run `git ship`
- the ship fails with an error message
- I resolve the conflicts
- I should be able to tell Git Town to just "continue" the last command. Instead I have to tell it to continue the ship.
- If I mix this up and tell Git Town to continue the last "sync", it creates an error message. So Git Town knows what operation I did last. It just forces me to type it up again.

So, maybe we introduce `git town continue` and `git town abort`?

**Comment by charlierudolph** [comment]
I'm going to work on #1016 and switching to the top level continue / abort then is fine by me
