### ISSUE TITLE
Strip ANSI color codes in branch names

### ISSUE THREAD

**Issue by alphatroya** [Originate/git-town#1131]
There is an error diring initial launch `hack` command
[![asciicast](https://asciinema.org/a/8DcTTlpfCCZhacMCiDE9gfnMg.png)](https://asciinema.org/a/8DcTTlpfCCZhacMCiDE9gfnMg) 

After all the `.git/config` file contains wrong branch names

```
[git-town]
    main-branch-name = [32mmaster[m
[git-town-branch "test"]
    parent = [32mmaster[m
```

Same issue after the `ship` command.

My git town version is 7.1.0

**Comment by charlierudolph** [comment]
Very odd. I'm not able to reproduce on my machine (MacOS Sierra - 10.12.6, fish shell). What operating system / shell are you using? 

We are making use of https://github.com/AlecAivazis/survey for prompts and passing in strings (which in our tests have never had colors). We get the prompt options from running branch `git branch`. 

It appears that by configuration colors, can be made to always be on instead of omitted if not output to a terminal. See the `Colors in Git` section here: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration. Can you please list your output of `git config -l`? (with any sensitive data scrubbed)

**Comment by alphatroya** [comment]
I use zsh shell with iTerm and High Siera. Problem remains when I switch terminal to bash or fish.

My config output is
```
credential.helper=osxkeychain
user.name=Alexey Korolev
user.email=alphatroya@gmail.com
core.editor=nvim
core.pager=diff-so-fancy | less --tabs=4 -RFX
core.excludesfile=/Users/alphatroya/.gitignore
merge.tool=vimdiff
mergetool.vimdiff.cmd=nvim $MERGED
commit.gpgsign=true
diff.tool=vimdiff
push.default=simple
gpg.program=/usr/local/bin/gpg
mergetool.keepbackup=false
color.ui=always
color.diff.meta=yellow bold
color.diff.commit=green bold
color.diff.frag=magenta bold
color.diff.old=red bold
color.diff.new=green bold
color.diff.whitespace=red reverse
color.diff-highlight.oldnormal=red bold
color.diff-highlight.oldhighlight=red bold 52
color.diff-highlight.newnormal=green bold
color.diff-highlight.newhighlight=green bold 22
credential.helper=osxkeychain
credential.https://github.com.username=alphatroya
```

**Comment by kevgo** [comment]
Thanks @alphatroya. Does it work if you change `color.ui=always` to `color.ui=true`? If you force Git to always output colors, then Git Town reads the branch name with colors when it calls Git to list all branches and gets confused. I have created #1132 to fix this on our end, but in the meantime this config change should hopefully resolve your issue.

**Comment by charlierudolph** [comment]
Thanks! 

Ok confirmed the issue can be caused by `color.ui=always`. For my understanding, what caused you to set that property?

We can use https://github.com/acarl005/stripansi to remove ansi colors for users with that property set. I'll try to write a failing feature test for this which should be easy enough.
