### ISSUE TITLE
git ship in offline mode leaves dangling branch on remote

### ISSUE THREAD

**Issue by grignaak** [Originate/git-town#1180]
Calling `git town ship` while in offline mode leaves a dangling remote branch, but no easy way to clean it up. There is a [git command][git-delete-remote] that does it, but judging by the stack overflow count on that question, it isn't as easy as it appears. Plus it has changed from git version to git version.

It would be super nice to be able to have `git town ship <feature>` such that if there is no local branch then it removes the remote branch.

[git-delete-remote]: https://stackoverflow.com/questions/2003505/how-do-i-delete-a-git-branch-both-locally-and-remotely

**Comment by kevgo** [comment]
Hey @grignaak, thanks for the feedback on Git Town! The idea behind offline mode is to allow working without an internet connection, for example on an airplane. It allows to keep working on existing feature branches and create new ones. Branches that were created locally can be shipped as well. If feature branches have remotes, they should not be shipped in offline mode. It is advised to wait until one has network connectivity again and then ship the finished branches. Git Town allows to keep all branches in sync in the meantime.

I strongly caution against programmatically deleting all feature branches on a remote that aren't on your machine. This would delete all feature branches of your co-workers. Because of this, we will not implement such a dangerous command in Git Town itself.

The proper solution for your situation is to delete the feature branch from the remote when shipping. For the setup you describe, where feature branches are on a different remote, I suggest you create your own wrapper script around Git Town's "ship" command. Let's call it "deliver" for the sake of example, you can name it anything you want. If you are on Linux, create a file "git-deliver" somewhere in your path, with this content:

```
#!/usr/bin/env bash

# determine the current branch name
BRANCHNAME=$(git branch | grep '*' | tr -d '* ')

# ship the current branch
git ship "$@"

# delete the remote branch
git push featureorigin :$BRANCHNAME
```

This assumes the origin where your feature branches live is named `featureorigin`.

Similar things can be achieved on Windows if you have Git Bash or Cygwin installed.
Don't forget to make it executable by running `chmod +x git-deliver`. This should solve your problem elegantly. Now you can run "git deliver" instead of "git ship" and it propely deletes your feature branch from the "featureorigin" remote.

Thanks for using Git Town, please don't hesitate to reach out with more questions!
