### ISSUE TITLE
How to avoid conflicts with ancestors?

### ISSUE THREAD

**Issue by rnystrom** [Originate/git-town#1294]
Hey all! This tool has been a lifesaver for my productivity and enabled me to use a dependent-PR workflow for a while.

One issue I'm struggling with is how to merge PRs using `git town ship` from the base when each branch modifies/extends on top of its ancestor.

Say I do:

- `git town hack feature-1`
- Add a new function `func doSomething(param: String)` with an implementation (using Swift as an example)
- Commit, etc
- `git town new-pull-request`
- `git town append feature-2`
- Extend previously-added function `func doSomething(param: String, anotherParam: Int`
- Commit, etc
- `git town new-pull-request`

I get a review for `feature-1` and `git town ship` it. However when I try to `git checkout feature-2` and `git town sync`, I end up getting conflicts.

> Note: maybe I don't get conflicts in my simple example, but hopefully you get the point.

In fact `feature-2`, while it points at `master`, has commits from `feature-1` in it. What I'd like to do instead is just have the original commits from `feature-2` and be able to merge cleanly into master without dealing with my own conflicts.

Am I doing something wrong? Or is there another way I should be working?

**Comment by kevgo** [comment]
Hi @rnystrom! These merge conflicts can happen when `feature-1` and `feature-2` in your example both make changes to the same line in the same file. It should be safe to accept the version in `feature-2` in that case, but it's always a good idea to pay attention when resolving merge conflicts.

Some background on why this happens: When shipping your `feature-1` branch, Git Town squash-merges all changes in that branch into a single commit on the main branch. That's a new commit that has no connection to the commits in `feature-1` anymore. When you then sync `feature-2`, Git sees the new commit on the main branch and conflicting changes on `feature-2`.

Your `feature-2` branch contains commits from `feature-1` because it was a child branch of it. This will get fixed when you ship `feature-2`: the resulting squashed commit on your main branch will only contain the changes that `feature-2` made. So it will all be good in the end if you trust Git Town 😉 

What you described seems the right behavior. You would run into these merge conflicts with other workflows as well, for example when rebasing your feature branches. The good news is that these types of conflicts happen only occasionally, and once resolved they don't re-appear.

**Comment by rnystrom** [comment]
@kevgo thanks for the info! The issue I run into is that I have to fix `feature-2`'s conflicts before shipping. Is that how its supposed to work?

**Comment by kevgo** [comment]
@rnystrom yes, to my understanding you have to fix the merge conflicts since they are "real" conflicts, i.e. two independent commits making changes to the same line in the same file. Git cannot resolve this type of conflict on its own (yet) and will trip over this in any situation.

You can try this out (without making permanent changes) on your setup (assuming your main branch is `master`):

```bash
git checkout master
git merge --no-commit feature-2
# you get merge conflicts here
# abort the failed merge attempt
git merge --abort
```

Even squash commits won't work here:

```bash
git checkout master
git merge --squash feature-2
# you get merge conflicts
# abort the failed merge attempt
git restore --staged .
git checkout .
```

So you have to deal with this. If you are absolutely sure that no other commits have been made to your main branch since you shipped `feature-1`, then you could automatically resolve all these merge conflicts by blindly accepting the state in `feature-2`:

```bash
# assuming you are on branch feature-2
# ran "git merge master" or "git town sync"
# and experience merge conflicts
grep -lr '<<<<<<<' . | xargs git checkout --ours
```

But beware, this can drop other changes made to `master` between `feature-1` and `feature-2` shipped. If you are sure none have happened, then feel free to do this. If not, then I don't see a way around reviewing and resolving the merge conflicts manually.

**Comment by kevgo** [comment]
I have added #1295 to track the idea of automatically resolving sync conflicts as discussed here. Since this is potentially destructive I need more experience around this before implementing it. I'll keep playing with it to see how well the idea holds up in real life.

**Comment by rnystrom** [comment]
Thanks for all the advice!
