### ISSUE TITLE
"non-feature" branch naming

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#344]
I was thinking about the naming we use... I believe we can come up with a better name. The "non-" negation makes it a bit confusing when trying to reason about the meaning of a "non-feature branch". 

We have three classes of branches now: 1) main, 2) feature, 3) non-feature.

Main and non-feature are treated similarly in many aspects, but when you see the words side-by-side, at first glance they feel like opposing classes, which is a bit misleading. This is especially apparent in the `git town config` output.

The naming just doesn't feel very fitting or intuitive to me. I see that "special" was considered at one point (https://github.com/Originate/git-town/pull/57). I think something similar to that would be more appropriate.

A likely positive side-effect would be having a shorter single-word name, for better symmetry with "main" (regarding https://github.com/Originate/git-town/pull/334).

Thoughts?

**Comment by charlierudolph** [comment]
I've disliked that as well. In some of the user value steps @kevgo mentioned "infrastructure" when talking about non feature branches. Not necessarily the word we should use but could lead us in the right direction.

**Comment by kevgo** [comment]
+1 I never liked that name. Some ideas that stormed out of my brain this morning:

* static branches
* permanent branches
* infrastructure branches
* release branches

I think "permanent" branches is the most generic and accurate of those. How do you feel about that?

**Comment by charlierudolph** [comment]
I was thinking along the lines of "release". Thats what this feature was originally created around. I think its fine if we are opinionated about what they are to start and wait for more user feedback.

**Comment by allewun** [comment]
Another idea is "environment" branch

**Comment by charlierudolph** [comment]
Another option I'm contemplating but unsure about is `stable branches`.

The options `infrastructure`, `release`, and `environment` are all opinionated about their purpose. Granted this is the only non-feature branches I've ever had, so I'm good with being opinionated. Of these I would vote for `release`.

`static` and `permanent` are more generic. If we are going the generic route I would vote for `static`.

**Comment by kevgo** [comment]
The branches aren't static, since they change all the time, so I think that option is out. I also don't like _"release"_ very much. For example on RMS we use the `sdk` branch, which is not a release branch.

That leaves _"permanent"_ branch with the most votes (Charlie and me) so far. Followed by opinionated names _"environment"_, _"infrastructure"_, and _"release"_. 

I renew my vote for _"permanent"_. That's really what these branches are: Long-lived branches that stick around, and aren't used for direct feature development. 

Nobody knows what these branches are used for: 
* releases
* old features that are kept around for historical purposes and cannot be synced anymore
* page hosting (like the `gh-pages` branch on GitHub)
* more stable versions of the main branch
* or whatever. 

Choosing an opinionated name just causes more confusion than we think here, and does so much sooner than we think. So let's avoid that if possible.

**Comment by allewun** [comment]
Kevin, I couldn't quite follow the 2nd half of your last comment (Nobody knows... and beyond).

I agree that we should choose a name carefully -- one that will stick around for good. We sound equally unsure about most of these, I think we need a bit more time before settling. I don't have a vote at the moment, but here are a few more ideas :)

* _special_ (I kind of like the original name, it's simple, has connotation that it's treated differently, has connotation that it's permanent)
* _domain_
* _protected_
* _supporting_ (from [here](http://nvie.com/posts/a-successful-git-branching-model/))
  * _auxiliary_ (more technical sounding version of supporting)

**Comment by charlierudolph** [comment]
Alright this discussion has shown me that we are trying to name a category of branches that could have too many purposes. I propose we throw out this idea all together of trying to name this category and instead move to a blacklist / whitelist approach.

At the moment no feature branches are treated in the following way
  * when syncing, rebase instead of merge and do not merge master
  * cannot be shipped

I believe we can replace this idea with the following:
* sync-merge-master-blacklist
  * names of branches that should not merge master when syncing
* sync-rebase-whitelist
  * names of branches that should rebase their tracking branch instead of merging 
* ship-blacklist
  * names of branches you want guards against shipping

The two sync lists way be able to combined, just us

**Comment by kevgo** [comment]
Implementing it internally this way is fine, but these lists should not be end-user facing. This is way too confusing and technical.

**Comment by allewun** [comment]
[Perennial](http://dictionary.reference.com/browse/perennial)?

**Comment by kevgo** [comment]
Perennial branches? I like it! :+1:

**Comment by kevgo** [comment]
Perennial plants keep growing over time, for many years. Unlike annual plants, which die off each year after their season is over. This maps well to how these branches behave.

**Comment by kevgo** [comment]
@charlierudolph @ricmatsui what do you think about "perennial branches"? I think this is the solution to our issue here.

**Comment by ricmatsui** [comment]
Perennial sounds good to me. It makes sense and has the branch-tree metaphor. While a blacklist/whitelist approach is probably always more powerful, I agree that it should at least provide some defaults like perennial that configures a branch in a clear way.

**Comment by charlierudolph** [comment]
Closing as this has been implemented
