### ISSUE TITLE
git pr: should push branch if necessary

### ISSUE THREAD

**Issue by retospect** [Originate/git-town#367]
For tiny changes, the following shuld work
```
git hack rs-foo
...
git commit -am "Some change"
git pr
```
git town will send me to an invalid pull request page. 
It should verify that the branch has been pushed before sending me there.

**Comment by charlierudolph** [comment]
I believe at the moment we are favoring that `git pr` stays minimal. We should be reporting an error though in this case. 

For your workflow I would suggest creating a git alias. I currently have the following
```
git acm 'commit message'
```
That stages all changes, commits with the given message and syncs.
You could create another alias that adds `git pr` to the end of it
I created my alias with
```
git config --global alias.acm '!f() { git add -A; git commit -m "$1"; git sync; }; f'
```

**Comment by kevgo** [comment]
@charlierudolph this would mean that Git Town is just another set of basic Git commands, and there needs to be another level of commands on top of Git Town necessary to actually use Git comfortably. I don't like that idea, especially not if doing this becomes a requirement. 

Git Town should be the thing that makes Git usable, without much further ado. I'm fine with keeping that to sane levels, and not trying to be everything to everybody. But pushing unpushed commits before creating a PR seems very reasonable and the right thing to do to me. I can't imagine a scenario where this is not what the user wants/expects. So given that Git Town should do this in my opinion.

**Comment by kevgo** [comment]
Thinking about this more, I vote for adding the sync operation to `git pr`. Not only is this the Right Thing To Do(tm), its also consistent with the behavior of `git ship` and `git hack`, which both perform a sync before they do their thing.

The shortcuts that @charlierudolph proposes would have to be created by literally every Git Town user. Users who don't define them would risk accidentally and unintentionally submitting incomplete PRs. There is no scenario in which not pushing unpushed feature commits before a PR even makes sense. 

Git Town's goal is to make Git usable out of the box. It's not a goal to just be another middle layer, at least for the majority of use cases. Because then I need another "Git Town"-like tool on top of Git Town, which defeats the whole purpose of this tool.

**Comment by kevgo** [comment]
@charlierudolph If I create an alias like `git acm`, and the sync fails, I cannot run `git acm --continue` or `git acm --abort`. I have to run `git sync --continue` or `git sync --abort`. 

This is a bad user experience, and it makes one feel Git Town stops somewhere in the middle, and doesn't go all the way as it could. Git Town should perform (and even enforce) the high-level workflow necessary for good and safe development, so that a team using Git Town doesn't run into issues with unsynchronized changes anymore. That's what this tool is all about.

**Comment by retospect** [comment]
Bump - 0.6 is still not syncing before opening a pull-request.

**Comment by kevgo** [comment]
This is one of the higher things on my list, since it bugs me each time I do a PR. I hope to get to it soon!

**Comment by kevgo** [comment]
I think this is rolled out now. Check it out @retospect!
