### ISSUE TITLE
Fish autocompletion bug

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#423]
Fish appears to autocomplete the command in wrong places
For example after another git command

```
> git add pr
pr  (Create a new pull request)  prune-branches  (Delete merged branches)
```
I was trying to autocomplete `git add p` to the file `package.json` but instead it autocompleted to `pr`

**Comment by kevgo** [comment]
This is intentional, at least for now. 

Initially the autocomplete was more specific. But the full graph of which things can/should be autocompleted in which situation is surprisingly complex. So I erred on the simple side, autocomplete everything all the time, and leave it up to the user to pick the right things.

**Comment by kevgo** [comment]
This is intentional, at least for now. 

Initially the autocomplete was more specific. But the full graph of which things can/should be autocompleted in which situation is surprisingly complex. So I erred on the simple side, autocomplete everything all the time, and leave it up to the user to pick the right things.

**Comment by kevgo** [comment]
Closing this for now since it works as intended, and there are no plans on fixing this on the roadmap. Please reopen if this changes.
