### ISSUE TITLE
git rename-branch

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#474]
`git rename-branch foo bar` renames the `foo` branch into `bar`, both on the local machine as well as on the remote.

**Comment by ricmatsui** [comment]
Should only feature branches be allowed to be renamed?

**Comment by kevgo** [comment]
Good question! I think that would be a useful security mechanism here, since in normal cases one would only want to rename feature branches. We could allow renaming the non-feature branches with a `-f` flag, thereby making the user think twice before doing it.

**Comment by ricmatsui** [comment]
Yeah I think that will work. Users will just have to be very careful since there could be issues with one developer renaming a non-feature branch, which would change the config so it's still a non-feature branch, and then another developer not updating their config causing the branch to be a feature branch on their side. We can include a warning to that effect.

**Comment by kevgo** [comment]
Good point. Renaming a non-feature branch should also update the config everywhere. Agreed that in the beginning it should display a message asking the user to do that manually.
