### ISSUE TITLE
improve cucumber scenario readability

### ISSUE THREAD

**Issue by allewun** [Originate/git-town#502]
https://github.com/cucumber/cucumber/wiki/Given-When-Then

1. What do you think about using "But" where appropriate (instead of "And")?
2. What about formatting the scenarios this way (with the leading keyword right aligned?)

```cucumber
Scenario: Multiple Givens
  Given one thing
    And another thing
    And yet another thing
   When I open my eyes
   Then I see something
    But I don't see something else
```

**Comment by kevgo** [comment]
I have been aware of "but" for a long time, but haven't seen an opportunity to use it. Every "but" can be better expressed as an "and" in my opinion. Not only in your example here ("And I don't see something else"), but also (spiritually speaking) in real life:

Instead of _"I see what you are saying, but I think we should do it this way anyways for these other reasons"_, we should say _"I see what you are saying, and I think we should do it this way anyways for these other reasons"_. The latter version expresses the same, and is more inclusive and understanding.

**Comment by kevgo** [comment]
In terms of aligning scenarios, I also tried that in the beginning, and didn't see it improving readability much. I'm not strongly feeling about any of those issues though, so I really am fine either way, as long as we stay consistent.

**Comment by ricmatsui** [comment]
I agree with `And` usually being better than `But` for the same reason. I think it negates the previous statement, too, so it would work much better in a case like:
```cucumber
When I open the folder
Then I see all the files
But I don't see any hidden files
```
since I don't actually see *all* the files.

I think the alignment works either way too.

**Comment by allewun** [comment]
Cool, just wanted to hear your thoughts. The obj-c in me kind of likes the right-aligned keywords, but I'm fine with our current approach.
