### ISSUE TITLE
git sync: configure to merge instead of rebase

### ISSUE THREAD

**Issue by charlierudolph** [Originate/git-town#671]
The screencast mentions this ability.

**Comment by charlierudolph** [comment]
* configuration to merge the main branch instead of rebasing
* configuration to merge perennial branches instead of rebasing

**Comment by kevgo** [comment]
This ticket is only for when it pulls the updates from the remote branch. As an example, right now for the master branch it does that through `git rebase origin/master`. This ticket is to add a configuration value `git-town.pull-branch-strategy`. If it has the value `merge`, then it runs `git pull origin/master`. In any other case it still runs `git rebase origin/master`.

**Comment by HangingClowns** [comment]
@kevgo is this possible, now, or the screencast is talking about the future? :dancers:

**Comment by kevgo** [comment]
@HangingClowns we are currently working on it!  :smiley:

**Comment by JaKXz** [comment]
@kevgo what about this vs #699? I personally prefer my working branch (made with `git hack`) to be rebased on `origin/<main-branch>` or `upstream/<main-branch>` rather than merged in... does the `--no-edit` drop the extra merge commits? I'd prefer `--ff-only` of all the [merge options](http://git-scm.com/docs/merge-options), if my understanding is correct.
