### ISSUE TITLE
make squash merge work with github flow

### ISSUE THREAD

**Issue by matthandlersux** [Originate/git-town#673]
@Bowbaq had a good idea. since git town likes to squash merge, but it closes your PR rather than merging... what if the flow was: git reset master -> make a single commit (the same commit that would be your squash commit) -> force push to your pull request -> click merge on github. this would allow other tools that look at the status of a pull request to still recognize when PRs get merged in.

**Comment by kevgo** [comment]
Great idea! That's the commit style that most open-source projects require (at least Rails does). All feature branches have to be squashed into a single commit, then merged together. I'm totally fine with adding a configuration option to Git Town to make `git ship` behave like this if desired.

I don't want to get rid of the current "squash commit" behavior, since it is the cleanest. The "squashed-merge" behavior described above requires two commits, and pollutes the history on master with a lot of  merge commits. I feel it is only so popular because of shortcomings of GitHub, particularly its inability to handle squash merges properly, even when it knows about them.

**Comment by matthandlersux** [comment]
yeah, i agree it is a workaround for the fact that github doesn't understand the squash/merge flow. still would be cool!

**Comment by acmcarther** [comment]
Is it possible to have a separate command added that just does the squash/merge and doesn't worry about the rest of the process? I think this has more utility than just for github-style merged, but a Git Town command like that would enable a github-style merge workflow without any debate about which style is better.

**Comment by kevgo** [comment]
@acmcarther do you mean something like `git squash-branch` that squashes all commits that exist in a feature branch into a single commit?

**Comment by matthandlersux** [comment]
@kevgo @acmcarther a second command (with docs that say "friendly with the way github tracks whether branches are merged") makes sense to me

**Comment by alexpeachey** [comment]
As an aside one company just starting to use git town really wants this
feature.
On Sat, Oct 10, 2015 at 4:11 PM matt handler <notifications@github.com>
wrote:

> @kevgo <https://github.com/kevgo> @acmcarther
> <https://github.com/acmcarther> a second command (with docs that say
> "friendly with the way github tracks whether branches are merged") makes
> sense to me
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Originate/git-town/issues/673#issuecomment-147133795>.
>
-- 

*Alex Peachey*Director of EngineeringOriginate - Las Vegas+ 1 702 376 2155

**Comment by kevgo** [comment]
One thing to keep in mind here is that as an individual command ("`git squash-branch`"), this will cause a rewrite of Git history, and hence require a force-push of the respective feature branch. Which will cause problems if there is more than one collaborator on the branch, if the branch has child branches, or the developer uses multiple machines to develop. So this is obviously dangerous, goes against best practices, and in my opinion is a Git anti-pattern, especially when a tool like Git Town is used.

The only situation where I see this being useful as a stand-alone command is when somebody makes a PR from a fork against the upstream repo without commit rights, and that repo requires single-commit feature branches (like for example the Rails project does).

If the developer has commit rights, this command has no use, because history will be squashed when shipping. So, at this point, I'm fine with extending `git ship` with a configuration option that instead of squash-merging into master, squashes all commits into one on the feature branch, and then merges that single-commit feature branch into the main branch, then deletes the branch. 

The only difference this would make is that GitHub shows "merged" instead of "closed". 

Is that what you have in mind here?

**Comment by acmcarther** [comment]
Generally, being able to use github's standard workflow would be a boon to a simpler github integration. Simply put, being able to squash-sync just as easily as I can ship or sync or hack would be amazing. Then I could push the green button, or keep working on my branch, same as people always have when they squash.

If we bundle that functionality into ship, that satisfies _most_ of my use cases though.

**Comment by acmcarther** [comment]
I don't want to miss also that this sort of merge strategy plays nicer with tools that integrate into github expecting pull requests to be merged, not closed, like Jira, or really anything using the github v3 api.

**Comment by kevgo** [comment]
Git Town is not just a loose set of git macros where one can pick whatever is useful and disregard the rest. That's what [git-extras](https://github.com/tj/git-extras) is. Using Git Town this way misses the point of it, and prevents most of the synergy between the different commands, as well as the value that this brings. 

Git Town is based on the idea that vanilla Git is too low-level and generic to be productive as an everyday developer tool. Hence we built an opinionated, high-level Git workflow support system that should be followed or extended instead of being avoided or fought against. It intentionally goes beyond the limitations of existing tools that are closer to vanilla Git (like GitHub), and does things better. 

Not using `git ship`, and using the green merge button on Github, for example, doesn't clean up shipped branches from the developer machine, and is completely incompatible with our "child branches" feature. So I'm 100% okay with extending `git ship` to perform squashed merges (this feature has been on our roadmap for a long time, and is even mentioned in the screen cast), but I'm against recommending to merge on GitHub. At least without further insights into how exactly that impacts the rest of Git Town.

I think what most people want are correctly merged PRs, not pressing the green button on GitHub, so this should address this requirement. What do you think?

**Comment by Bowbaq** [comment]
Honestly, if it doesn't play nice with the GitHub lifecycle, that's a show stopper for me. The fact that PRs get closed instead of being merged breaks an assumption baked into GitHub, and into all the tools that interface with it. It doesn't matter to me if things get merged in the UI, or by an API call (which would allow to do whatever cleanup is needed)

**Comment by kevgo** [comment]
The improved `git ship` command that performs traditional merges is fully compatible with GitHub's lifecycle.

**Comment by alexpeachey** [comment]
There are a number of scenarios where the merge button on GitHub needs to be used and/or the outcome of using it is desired. The two biggest that come to mind are:

1. On an OSS project you contribute to, they often have rules where a single person or group of people merge and merge by using the button on GitHub. Having an option to do the squashing, force pushing, and prepping the branch on the PR for merge with the button is desired here. There are downsides as pointed out like branch cleanup cannot happen, etc.

2. On a project that is housed on GitHub, some tools expect the PRs to be closed with a merge using the button on GitHub. There is also a visible difference looking at PRs closed by Git Town and PRs closed via the GitHub button. Many organizations do not like these differences. It's not that they want to see the little merge bubbles, what they want is for it to look like a "normal" GitHub project. Having an option here that would squash, force push to the PR branch, use the GitHub API to merge, and then clean up all branches would be desired here. You get all the benefits of the current `git ship`, but with the added benefit of it looking "normal" on GitHub.

**Comment by kevgo** [comment]
Cool, great suggestions and conversation everybody! These are legitimate use cases. So it looks like we need to add a new configuration option called "ship-using-merges" (or something like that). When activated, it changes the behavior of several Git Town commands:

* `git new-pull-request` squashes the commits into one before creating the pull request. This is safe, since that commit squashing has to happen anyways when shipping. So we can as well do it now. This allows to use the green merge button on GitHub without adding a mess to the main branch.

* `git ship` re-squashes commits again if there are multiple commits in the feature branch, then does a normal merge.

* `git prune-branches` can use a different strategy that allows it to find branches that have already been shipped more reliably now.

When making a pull request against an upstream repo, the "ship-using-merges" mode is automatically activated, even when it is otherwise disabled.

This configuration option is set per repository. I'm fine making "ship-using-merges" the default, because its more idiot proof and compatible.

@charlierudolph @allewun @ricmatsui what do you think?

**Comment by kevgo** [comment]
@charlierudolph would love to hear your take on this, since I'm thinking about taking this one on as one of the next steps. This is a major improvement in compatibility with GitHub, but it also adds a good amount of complexity.

**Comment by allewun** [comment]
> * `git new-pull-request` squashes the commits into one before creating the pull request. This is safe, since that commit squashing has to happen anyways when shipping. So we can as well do it now. This allows to use the green merge button on GitHub without adding a mess to the main branch.

I find value in preserving commit history for a pull-request when reviewing a PR. Am I alone in this?

**Comment by kevgo** [comment]
Yeah, that's a downside of this approach. Ideally even commits that address changes get squashed away here. If we don't do this aggressively, we run into the issue that somebody clicks the big green "merge" button on GitHub, and we mess up the Git history with WIP commits.

**Comment by kevgo** [comment]
Overall the Git Town team agrees that advantages of this approach seem to outweigh the disadvantages, so we are going to make this the new standard behavior.

I have created milestone [GitHub compatible merging behavior](https://github.com/Originate/git-town/milestones/GitHub-compatible%20merging%20option) to track development of this feature. It contains tickets #705, #706, and #707 that allow us to build this functionality in pieces.

Thanks for the suggestion and the great feedback, please keep it coming!

**Comment by matthandlersux** [comment]
cool!

**Comment by charlierudolph** [comment]
Closing as 4.2.0 now merges via the GitHub API when applicable
