### ISSUE TITLE
git-sync use "rebase" replace "merge"

### ISSUE THREAD

**Issue by MasonLiuChn** [Originate/git-town#699]
git-sync default use "merges the parent branch into the current branch"

i think "rebase the current branch to the parent branch" is more convenient.

or add a parameter

**Comment by JaKXz** [comment]
+1 for this.

**Comment by charlierudolph** [comment]
If we rebase with branches that have been pushed to a remote repository, it will require a force push. Thats fine for feature branches, but just something I prefer to use minimally.

**Comment by kevgo** [comment]
Thanks for the suggestion! Please keep in mind that in the Git Town world, one uses `git ship` to merge completed feature branches back into the main branch. `git ship` squashes the feature branch into a single commit before merging. So the particular strategy (merge vs rebase) how feature branches get updated while being developed doesn't matter much in the grand scheme of things, since they both end in the same result once the branch is shipped.

We chose to use merges instead of rebases for multiple reasons:
1. if there are merge conflicts while pulling, one has to resolve them only once for merges, but multiple times for rebases
2. rebasing requires a force-push, which is really problematic when a branch is shared between several developers or machines, because it now becomes impossible to do a `git pull` on the other machine

All of this together makes me hesitant to implement rebases here, or even add a configuration option. I don't see any advantages, and lots of disadvantages. Git Town is designed to make Git easy and robust.

@MasonLiuChn and @JaKXz, what are your reasons to prefer rebases here? Is it just because that's how one would do that normally (without Git Town), or are there other specific reasons?

**Comment by JaKXz** [comment]
@kevgo thanks for the detailed answer! I didn't really know about `git ship` hence my question (since I was doing the squashing manually and was a bit tedious, but I guess less tedious than getting merge conflicts wrong). 

Does `git ship` create a merge commit with the parent branch? It would be great if it didn't so I could just make a PR and review it with my colleagues

**Comment by JaKXz** [comment]
@kevgo after looking at the [docs for `git ship`](https://github.com/Originate/git-town/blob/master/documentation/commands/git-ship.md) I see the `commit-options` option, but how can I specify that I don't want the merge to happen?

**Comment by kevgo** [comment]
@JaKXz git `git-ship` right now creates a normal commit on the main branch that contains the changes from the feature branch, then it deletes the feature branch. No merge commit, but a simple normal commit. See [here](https://github.com/Originate/git-town/blob/master/features/git-ship/current_branch/on_feature_branch/without_open_changes/with_tracking_branch.feature) for an example which commands exactly it runs in the most straightforward use case. Also, have you checked out the screen cast on git-town.com? It explains the different commands, what they do, and how they work together.

**Comment by JaKXz** [comment]
@kevgo thanks again for the reply. I'd seen the screen-cast, but I still don't see the case for deleting the branch and making the commit on top of the main branch. I think the typical git flow, even for those working from forks is to make a PR from your working branch, and then when the PR is merged you can use GitHub to delete the branch from your remote. (aside: this is where `prune-branches` for your fork only #356 would be nice).

I think `git ship` is a great convenience method for squashing all commits in the feature branch, but the way it is right now, I have to take extra steps to re-create the branch, `cherry-pick` the new commit, then reset my main branch to the commit before.

**Comment by JaKXz** [comment]
@kevgo but to come back to the actual topic of this issue, I think `git sync`, when on a feature branch should just checkout the main branch, do a regular `git sync`, and then come back to the feature branch and rebase it on the local copy of the main branch.

**Comment by JaKXz** [comment]
I have this `rebaseme` alias in my `.bash_profile`, which requires that you specify the main branch:

```bash
rebaseme ()
{
    local BRANCH=$(git rev-parse --abbrev-ref HEAD);
    git checkout "$1" && git sync && git co $BRANCH && git rebase "$1"
}
```

**Comment by JaKXz** [comment]
More awesome (according to me, a non-bash programmer) version of `rebaseme`

```bash
function rebaseme ()
{
    if [ -z $1 ]; then 
        local BASE="master";
    else
        local BASE=$1;
    fi
    echo "rebasing on $BASE branch, are you sure? [Y/n]";
    read input;
    if [[ $input == "N" || $input == "n" ]]; then
        echo "not rebasing!";
    else
        local BRANCH=$(git rev-parse --abbrev-ref HEAD);
        git co $1 && git sync && git co $BRANCH && git rebase $1;
    fi
}
```

**Comment by kevgo** [comment]
@JaKXz so on the "main" branch `git sync` actually rebases the local branch against the remote branch. This is documented in our [tests](https://github.com/Originate/git-town/blob/master/features/git-sync/current_branch/main_branch/no_conflict/with_tracking_branch.feature#L23). Same for perennial (long-lived) branches, see [here](https://github.com/Originate/git-town/blob/master/features/git-sync/current_branch/perennial_branch/no_conflict/with_tracking_branch.feature#L26).

So Git Town already does what this ticket has in mind for long-lived branches. If you are on a feature branch, I'm against rebasing. Because (A) merges are safer and easier to resolve when there are conflicts, (B) they don't require a force-push (which breaks other people or machines who have checked out this branch), and (C) when the branch is shipped, all the merge commits get squashed away. So in the end the merge strategy for feature branches doesn't matter at all if you use `git ship`.

@JaKXz and @MasonLiuChn I recommend you check out `git ship`, its another cool time and headache saver, and it addresses the issues you raise here.
