### ISSUE TITLE
Unable to git ship with un-added files

### ISSUE THREAD

**Issue by ssebelius** [Originate/git-town#718]
I have untracked files in my repository and am trying to run git ship on a branch. When running git ship I get the error `You cannot ship with uncommitted changes`.

Is this by design?

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	some_image.png
	some_image_2.png
	public/v1/admin/

nothing added to commit but untracked files present (use "git add" to track)
> ssebelius$ git ship

  Error
  You cannot ship with uncommitted changes.
```

**Comment by charlierudolph** [comment]
This was part of the original design. If you have uncommitted files, the assumption is you have changes that you want to ship but you forgot to commit them. 

We can update the error message to explain this a bit better. Maybe updating it to:
```
Error
You have uncommitted changes. Did you mean to commit these before shipping?
If not please stash them before shipping. 
```

Introducing an option to stash uncommitted changes would be hard as we currently pass all options to the eventual `git commit`.

**Comment by allewun** [comment]
I also brought this up back in #139, but I think the intent @charlierudolph described is probably for good reason.

+1 to the updated message.

FWIW, I've since alleviated this problem with an enhanced [git stash alias](https://github.com/allewun/dotfiles/blob/master/.gitconfig#L52).

**Comment by ssebelius** [comment]
+1 the updated message as well.

I understand the reason behind it. In my case I knew the untracked files were there and did not want to commit or ship them. Simple enough to work around, but it took an additional 4 commands:

```
git commit
git stash
git ship
git stash pop
git revert HEAD
```

**Comment by charlierudolph** [comment]
Why is the `git commit` and `git revert HEAD` needed? 
Also can these untracked files just be added to gitignore?

**Comment by ssebelius** [comment]
`commit` and `revert HEAD` were to make sure stash worked with tracked files.  Looks like I should have just used `git stash --include-untracked` and those would not have been necessary.

**Comment by kevgo** [comment]
@ssebelius if you don't want to commit these files, how about adding them to `.gitignore` for your repo? That way you can keep them forever, and they don't interfere with other Git operations as well, like adding, committing, diffing etc.

**Comment by charlierudolph** [comment]
@kevgo @allewun @ssebelius how do you feel about adding a question instead of the outright error? So when you ship the current branch with uncommitted changes, you get a prompt
```
You have uncommitted changes. Did you mean to commit these before shipping?

1) abort
2) stash my uncommitted changes and ship <branch-name>

Please select what you would like to do by number: 
```

**Comment by kevgo** [comment]
Git Town is to encourage and support a certain "responsible" development workflow. This includes only shipping fully tested changes. If we stash away some files before shipping, but these files were used for testing, we introduce more possibilities for breakage on master. 

Another concern is that this introduces a ton of complexity and headaches for the shipping process. If we stash, we must also unstash after the ship. This can lead to conflicts, that cause a perfectly fine ship to fail. If the ship fails at this stage, it is impossible to undo the ship, since commits have already been pushed to origin. The user is left with a perfectly fine, but incomplete ship. 

Overall this feels like an improper usage scenario. I think in the vast majority of cases shipping with uncommitted changes or files is not intended, and not the right way to develop software. I don't want to make the edge case of somebody having uncommitted files, and these files are not planned to be committed, and they are also not being added to gitignore for some reason, too easy. 

If we add support for something in Git Town, this means we approve and encourage this type of development, and make it "officially supported". I'm against doing this here. I'll close this. If there is a lot of demand for this feature, together with some legitimate and widespread use cases, I'm happy to reconsider.
