### ISSUE TITLE
Feature request: git wip - Make a wip (Work in Progress) commit

### ISSUE THREAD

**Issue by atilacamurca** [Originate/git-town#725]
The ideia is to make a WIP (Work in Progress) commit that we can easily sync with a feature branch.

The command must stage all modified and untracked files.
Commit those files with a WIP message, indicating that is a work in progress commit.

This will make easy to change branches without having to stash changes.

**Comment by charlierudolph** [comment]
Can you please explain a little more? What git command or commands would this run?

**Comment by atilacamurca** [comment]
Thinking better this command is simple as this alias

`alias gwip='git add -A; git rm $(git ls-files --deleted) 2> /dev/null; git commit -m "--wip--"'`

If you guys want you may close this issue.

**Comment by atilacamurca** [comment]
Rethink again I just found a situation that may be the case for a wip and unwip commands.

This was taken from the `git help reset` documentation:

~~~
Interrupted workflow
           Suppose you are interrupted by an urgent fix request while you are
           in the middle of a large change. The files in your working tree
           are not in any shape to be committed yet, but you need to get to
           the other branch for a quick bugfix.

               $ git checkout feature ;# you were working in "feature" branch and
               $ work work work       ;# got interrupted
               $ git commit -a -m "snapshot WIP"                 (1)
               $ git checkout master
               $ fix fix fix
               $ git commit ;# commit with real log
               $ git checkout feature
               $ git reset --soft HEAD^ ;# go back to WIP state  (2)
               $ git reset                                       (3)

           1. This commit will get blown away so a throw-away log message is
           OK.
           2. This removes the WIP commit from the commit history, and sets
           your working tree to the state just before you made that snapshot.
           3. At this point the index file still has all the WIP changes you
           committed as snapshot WIP. This updates the index to show your WIP
           files as uncommitted.
~~~

So the ideia is to have a `wip` command to make the **(1)**, and an `unwip` command to execute **(2)** and **(3)**.

**Comment by kevgo** [comment]
I run into this situation a lot on my projects, so +1 on the scenario. I believe in the Git Town workflow the solution is to simply make the temporary commit into the feature branch and leave it there. Because all commits will be squashed when shipping, commits in feature branches don't have to look nice, can be incomplete, and break builds without long-term consequences. When you continue working on the feature branch after the hot-fix, simply look at the temporary commit and continue where you left off. 

If you want to avoid the temporary commit for whatever reason, then `git stash -u` seems like the better way to get open changes out of the way temporarily.
