### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by kevgo** [Originate/git-town#735]
@charlierudolph @allewun what do you think is missing for a 1.0 release? I'm personally okay declaring the current version stable, since it hasn't changed in a year or so.

**Comment by charlierudolph** [comment]
I think we are good for 1.0. I can get in the one open PR in today and then do a release if we are ready. 

The only big thing in our [milestones](https://github.com/Originate/git-town/milestones) is the github compatible stuff, but since Github released the ability to squash merge I don't know if that's necessary.

**Comment by kevgo** [comment]
Sounds great! I see platform specific things like GitHub support more in extensions/plugins than the core product. And most likely these things will be incremental, i.e. minor version bumps. If not, a good reason to release a 2.0 version next year!

**Comment by charlierudolph** [comment]
Homebrew/homebrew-core#3649

**Comment by charlierudolph** [comment]
Homebrew PR is merged. Git-town 1.0 is released.

@allonsy can you please update the linux releases (if needed) and close this issue when you are done?

**Comment by kevgo** [comment]
Thanks @charlierudolph !!

**Comment by allonsy** [comment]
Ubuntu deb files are done, will update arch linux tonight

**Comment by allonsy** [comment]
arch linux package has been released

**Comment by charlierudolph** [comment]
Thanks @allonsy!

**Comment by kevgo** [comment]
👏
