### ISSUE TITLE
git-town hack does not push new branch or track upstream

### ISSUE THREAD

**Issue by JaKXz** [Originate/git-town#966]
Hi, I think this might be related to #859 but I believe this is has broken within the v4 branch... if the behaviour was changed on purpose I believe that this should have been a breaking change (i.e. major semver version).

**Comment by charlierudolph** [comment]
The default for whether or not new branches are pushed was changed to false. See #929. We didn't consider a breaking change.

**Comment by JaKXz** [comment]
I don't see this as a bug fix.

[The original definition of this command](https://github.com/Originate/git-town/blob/acc128bed6146d005472c1417026a2f79e7184f1/documentation/commands/hack.md) says that the branch will be pushed and tracked upstream. Therefore changing it is breaking existing behaviour and warrants a major semver change. 

While I appreciate that this is your tool and developed for your purposes, it would be nice to know whether or not you are respecting semver. If you are not, that's fine as your purview, but I'd like to clear the air here.

Also, I tried setting:

```
git town hack-push-flag true
```

but new branches are not pushed even after restarting my terminal:

```
~/code/git-town
$ git-town hack testing

[master] git fetch --prune

[master] git rebase origin/master
Current branch master is up to date.

[master] git fetch upstream

[master] git rebase upstream/master
Current branch master is up to date.

[master] git checkout -b testing master
Switched to a new branch 'testing'
```

so, I don't think this issue should just be closed without further discussion.

**Comment by charlierudolph** [comment]
We are trying to respect semver. The change was also documented in our release notes and on the releases page. See the issue for why we didn't consider it a breaking change. I originally thought it was.  

Hack-push-flag is a per repo configuration. We could implement an ability to set it globally so you can make it the default for new repos. If this is desired, please create a separate issue for this.

**Comment by JaKXz** [comment]
@kevgo since this was a change to default behaviour that breaks for those who did not change or know of the `hack-push-flag` setting, I don't see it as a [backwards compatible new feature, as defined by semver](http://semver.org). The backwards compatible approach would have been to create the global setting for `hack-push-flag` and inform users to set it for the projects they need as appropriate (ie global false, and if there are projects where it's ok, the locally true) IMHO. 

I'm not disparaging the documentation of the change (in the release notes etc), just offering my 2c on what is in fact a reasonable feature and the way it was introduced. 

In the past you guys have been very good about making major versions for changes and it was a nice indicator that the project had moved forward. Expressing my concern/retrospective like this because it was a disruptive surprise that I think could have been avoided.

**Comment by kevgo** [comment]
@JaKXz thanks for voicing your concerns. We hear you and thought about the same things, and decided that a minor version bump is a more pragmatic solution here. 

Version 4.1 changes a default configuration setting that doesn't affect the user-facing interface of Git Town. One can still run `git hack`, `git sync`, `git ship`, and any other Git Town command exactly as before. One can also still commit changes as before. The only difference is some fine-tuning when new branches are pushed to origin during this workflow by default. This only affects undocumented behavior: running `git push`  instead of `git sync`. Undocumented behavior changes don't need to be reflected in semantic versioning. Please note that one is supposed to use `git sync` to push changes to origin because that also keeps the branch in sync. 

This change also does not affect any existing branches (which are already pushed to origin). Hence we consider it more of a new feature for new branches moving forward, rather than a breaking change. 

Perfect semantic versioning is an illusion. Every bug fix is a change of existing behavior. Some users might depend on the buggy behavior. So when fixing the bug one might break those users. Even a simple performance improvement can cause different timings and thereby break some people who depend on the old timing (not in Git Town, but in other software). Git Town adheres to the idea of semantic versioning but within reason. 

Because of all these considerations, we decided to make this a minor version bump and document the change in the release notes. 

If the new setting does not work for you, please file a complete bug report including the output of `git config -l` for your repo (sanitize confidential data away), and we'll take a look. Thanks!
